"""
Local demo movie catalogue used when TMDB credentials are absent.
Covers every major genre so the UI is fully populated.
"""

from __future__ import annotations

DEMO_GENRES: list[dict] = [
    {"id": 28, "name": "Action"},
    {"id": 12, "name": "Adventure"},
    {"id": 16, "name": "Animation"},
    {"id": 35, "name": "Comedy"},
    {"id": 80, "name": "Crime"},
    {"id": 99, "name": "Documentary"},
    {"id": 18, "name": "Drama"},
    {"id": 10751, "name": "Family"},
    {"id": 14, "name": "Fantasy"},
    {"id": 36, "name": "History"},
    {"id": 27, "name": "Horror"},
    {"id": 10402, "name": "Music"},
    {"id": 9648, "name": "Mystery"},
    {"id": 10749, "name": "Romance"},
    {"id": 878, "name": "Science Fiction"},
    {"id": 53, "name": "Thriller"},
    {"id": 10752, "name": "War"},
    {"id": 37, "name": "Western"},
]

# fmt: off
DEMO_MOVIES: list[dict] = [
    # ── Action ──
    {"id": 155, "title": "The Dark Knight", "overview": "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", "release_date": "2008-07-18", "vote_average": 8.5, "runtime": 152, "genre_ids": [28, 18, 80], "genres": [{"id": 28, "name": "Action"}, {"id": 18, "name": "Drama"}, {"id": 80, "name": "Crime"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 1, "name": "Christian Bale", "character": "Bruce Wayne / Batman", "profile_path": None}], "crew": [{"id": 525, "name": "Christopher Nolan", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 24428, "title": "The Avengers", "overview": "When an unexpected enemy emerges and threatens global safety, Nick Fury assembles a team of superheroes to save the world.", "release_date": "2012-05-04", "vote_average": 7.7, "runtime": 143, "genre_ids": [28, 12, 878], "genres": [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 878, "name": "Science Fiction"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [], "crew": [{"id": 12891, "name": "Joss Whedon", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 27205, "title": "Inception", "overview": "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", "release_date": "2010-07-16", "vote_average": 8.4, "runtime": 148, "genre_ids": [28, 878, 12], "genres": [{"id": 28, "name": "Action"}, {"id": 878, "name": "Science Fiction"}, {"id": 12, "name": "Adventure"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 6193, "name": "Leonardo DiCaprio", "character": "Dom Cobb", "profile_path": None}], "crew": [{"id": 525, "name": "Christopher Nolan", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 98, "title": "Gladiator", "overview": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.", "release_date": "2000-05-05", "vote_average": 8.2, "runtime": 155, "genre_ids": [28, 18, 12], "genres": [{"id": 28, "name": "Action"}, {"id": 18, "name": "Drama"}, {"id": 12, "name": "Adventure"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 934, "name": "Russell Crowe", "character": "Maximus", "profile_path": None}], "crew": [{"id": 578, "name": "Ridley Scott", "job": "Director"}]}, "videos": {"results": []}},

    # ── Adventure ──
    {"id": 11, "title": "Star Wars", "overview": "Princess Leia is captured by the villainous Darth Vader. Luke Skywalker joins forces with a Jedi Knight to rescue her and save the galaxy.", "release_date": "1977-05-25", "vote_average": 8.2, "runtime": 121, "genre_ids": [12, 28, 878], "genres": [{"id": 12, "name": "Adventure"}, {"id": 28, "name": "Action"}, {"id": 878, "name": "Science Fiction"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 2, "name": "Mark Hamill", "character": "Luke Skywalker", "profile_path": None}], "crew": [{"id": 1, "name": "George Lucas", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 85, "title": "Raiders of the Lost Ark", "overview": "Archaeologist and adventurer Indiana Jones is hired to find the Ark of the Covenant before the Nazis can obtain its awesome powers.", "release_date": "1981-06-12", "vote_average": 8.3, "runtime": 115, "genre_ids": [12, 28], "genres": [{"id": 12, "name": "Adventure"}, {"id": 28, "name": "Action"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 3, "name": "Harrison Ford", "character": "Indiana Jones", "profile_path": None}], "crew": [{"id": 488, "name": "Steven Spielberg", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 120, "title": "The Lord of the Rings: The Fellowship of the Ring", "overview": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth.", "release_date": "2001-12-19", "vote_average": 8.4, "runtime": 178, "genre_ids": [12, 14, 28], "genres": [{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 109, "name": "Elijah Wood", "character": "Frodo", "profile_path": None}], "crew": [{"id": 108, "name": "Peter Jackson", "job": "Director"}]}, "videos": {"results": []}},

    # ── Animation ──
    {"id": 862, "title": "Toy Story", "overview": "A cowboy doll is profoundly threatened when a new spaceman figure supplants him as top toy in a boy's room.", "release_date": "1995-11-22", "vote_average": 8.0, "runtime": 81, "genre_ids": [16, 35, 10751], "genres": [{"id": 16, "name": "Animation"}, {"id": 35, "name": "Comedy"}, {"id": 10751, "name": "Family"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 31, "name": "Tom Hanks", "character": "Woody", "profile_path": None}], "crew": [{"id": 7879, "name": "John Lasseter", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 129, "title": "Spirited Away", "overview": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.", "release_date": "2001-07-20", "vote_average": 8.5, "runtime": 125, "genre_ids": [16, 10751, 14], "genres": [{"id": 16, "name": "Animation"}, {"id": 10751, "name": "Family"}, {"id": 14, "name": "Fantasy"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [], "crew": [{"id": 608, "name": "Hayao Miyazaki", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 150540, "title": "Inside Out", "overview": "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions conflict on how best to navigate a new city.", "release_date": "2015-06-19", "vote_average": 8.0, "runtime": 95, "genre_ids": [16, 35, 18], "genres": [{"id": 16, "name": "Animation"}, {"id": 35, "name": "Comedy"}, {"id": 18, "name": "Drama"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [], "crew": [{"id": 12898, "name": "Pete Docter", "job": "Director"}]}, "videos": {"results": []}},

    # ── Comedy ──
    {"id": 120467, "title": "The Grand Budapest Hotel", "overview": "The adventures of Gustave H, a legendary concierge at a famous hotel, and Zero Moustafa, the lobby boy who becomes his most trusted friend.", "release_date": "2014-03-28", "vote_average": 8.1, "runtime": 99, "genre_ids": [35, 18], "genres": [{"id": 35, "name": "Comedy"}, {"id": 18, "name": "Drama"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 5, "name": "Ralph Fiennes", "character": "Gustave H", "profile_path": None}], "crew": [{"id": 5655, "name": "Wes Anderson", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 13, "title": "Forrest Gump", "overview": "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man with a low IQ.", "release_date": "1994-07-06", "vote_average": 8.5, "runtime": 142, "genre_ids": [35, 18, 10749], "genres": [{"id": 35, "name": "Comedy"}, {"id": 18, "name": "Drama"}, {"id": 10749, "name": "Romance"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 31, "name": "Tom Hanks", "character": "Forrest Gump", "profile_path": None}], "crew": [{"id": 24, "name": "Robert Zemeckis", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 425, "title": "Superbad", "overview": "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.", "release_date": "2007-08-17", "vote_average": 7.2, "runtime": 113, "genre_ids": [35], "genres": [{"id": 35, "name": "Comedy"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 21007, "name": "Jonah Hill", "character": "Seth", "profile_path": None}], "crew": [{"id": 57130, "name": "Greg Mottola", "job": "Director"}]}, "videos": {"results": []}},

    # ── Crime ──
    {"id": 238, "title": "The Godfather", "overview": "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.", "release_date": "1972-03-14", "vote_average": 8.7, "runtime": 175, "genre_ids": [80, 18], "genres": [{"id": 80, "name": "Crime"}, {"id": 18, "name": "Drama"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 380, "name": "Marlon Brando", "character": "Don Vito Corleone", "profile_path": None}], "crew": [{"id": 1776, "name": "Francis Ford Coppola", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 680, "title": "Pulp Fiction", "overview": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", "release_date": "1994-10-14", "vote_average": 8.5, "runtime": 154, "genre_ids": [80, 53], "genres": [{"id": 80, "name": "Crime"}, {"id": 53, "name": "Thriller"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 139, "name": "John Travolta", "character": "Vincent Vega", "profile_path": None}], "crew": [{"id": 138, "name": "Quentin Tarantino", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 769, "title": "GoodFellas", "overview": "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.", "release_date": "1990-09-19", "vote_average": 8.5, "runtime": 146, "genre_ids": [80, 18], "genres": [{"id": 80, "name": "Crime"}, {"id": 18, "name": "Drama"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 380, "name": "Ray Liotta", "character": "Henry Hill", "profile_path": None}], "crew": [{"id": 1032, "name": "Martin Scorsese", "job": "Director"}]}, "videos": {"results": []}},

    # ── Drama ──
    {"id": 278, "title": "The Shawshank Redemption", "overview": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", "release_date": "1994-09-23", "vote_average": 8.7, "runtime": 142, "genre_ids": [18, 80], "genres": [{"id": 18, "name": "Drama"}, {"id": 80, "name": "Crime"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 504, "name": "Tim Robbins", "character": "Andy Dufresne", "profile_path": None}], "crew": [{"id": 4027, "name": "Frank Darabont", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 550, "title": "Fight Club", "overview": "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.", "release_date": "1999-10-15", "vote_average": 8.4, "runtime": 139, "genre_ids": [18], "genres": [{"id": 18, "name": "Drama"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 819, "name": "Edward Norton", "character": "The Narrator", "profile_path": None}], "crew": [{"id": 7467, "name": "David Fincher", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 389, "title": "12 Angry Men", "overview": "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence.", "release_date": "1957-04-10", "vote_average": 8.5, "runtime": 96, "genre_ids": [18], "genres": [{"id": 18, "name": "Drama"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 1924, "name": "Henry Fonda", "character": "Juror 8", "profile_path": None}], "crew": [{"id": 59839, "name": "Sidney Lumet", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 497, "title": "The Green Mile", "overview": "A tale set on death row in a Southern prison where gentle giant John Coffey possesses the mysterious power to heal people's ailments.", "release_date": "1999-12-10", "vote_average": 8.5, "runtime": 189, "genre_ids": [18, 14, 80], "genres": [{"id": 18, "name": "Drama"}, {"id": 14, "name": "Fantasy"}, {"id": 80, "name": "Crime"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 31, "name": "Tom Hanks", "character": "Paul Edgecomb", "profile_path": None}], "crew": [{"id": 4027, "name": "Frank Darabont", "job": "Director"}]}, "videos": {"results": []}},

    # ── Fantasy ──
    {"id": 671, "title": "Harry Potter and the Philosopher's Stone", "overview": "An orphaned boy enrolls in a school of wizardry where he learns the truth about himself, his family, and the terrible evil that haunts the magical world.", "release_date": "2001-11-16", "vote_average": 7.9, "runtime": 152, "genre_ids": [14, 12], "genres": [{"id": 14, "name": "Fantasy"}, {"id": 12, "name": "Adventure"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 10980, "name": "Daniel Radcliffe", "character": "Harry Potter", "profile_path": None}], "crew": [{"id": 10965, "name": "Chris Columbus", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 22881, "title": "The Princess Bride", "overview": "While home sick in bed, a young boy's grandfather reads him the story of a farmboy-turned-pirate who encounters numerous obstacles rescuing his true love.", "release_date": "1987-10-09", "vote_average": 7.9, "runtime": 98, "genre_ids": [14, 12, 35, 10749], "genres": [{"id": 14, "name": "Fantasy"}, {"id": 12, "name": "Adventure"}, {"id": 35, "name": "Comedy"}, {"id": 10749, "name": "Romance"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [], "crew": [{"id": 1366, "name": "Rob Reiner", "job": "Director"}]}, "videos": {"results": []}},

    # ── Horror ──
    {"id": 694, "title": "The Shining", "overview": "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son witnesses horrific forebodings.", "release_date": "1980-05-23", "vote_average": 8.2, "runtime": 146, "genre_ids": [27, 53], "genres": [{"id": 27, "name": "Horror"}, {"id": 53, "name": "Thriller"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 514, "name": "Jack Nicholson", "character": "Jack Torrance", "profile_path": None}], "crew": [{"id": 240, "name": "Stanley Kubrick", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 493922, "title": "Hereditary", "overview": "When the matriarch of the Graham family passes away, her daughter and grandchildren begin to unravel cryptic and increasingly terrifying secrets.", "release_date": "2018-06-08", "vote_average": 7.3, "runtime": 127, "genre_ids": [27, 9648, 53], "genres": [{"id": 27, "name": "Horror"}, {"id": 9648, "name": "Mystery"}, {"id": 53, "name": "Thriller"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 5081, "name": "Toni Collette", "character": "Annie Graham", "profile_path": None}], "crew": [{"id": 1735548, "name": "Ari Aster", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 539, "title": "Psycho", "overview": "A Phoenix secretary embezzles forty thousand dollars from her employer's client, goes on the run, and checks into a remote motel run by a young man under his mother's domination.", "release_date": "1960-06-16", "vote_average": 8.4, "runtime": 109, "genre_ids": [27, 53, 9648], "genres": [{"id": 27, "name": "Horror"}, {"id": 53, "name": "Thriller"}, {"id": 9648, "name": "Mystery"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 5765, "name": "Anthony Perkins", "character": "Norman Bates", "profile_path": None}], "crew": [{"id": 2636, "name": "Alfred Hitchcock", "job": "Director"}]}, "videos": {"results": []}},

    # ── Mystery / Thriller ──
    {"id": 807, "title": "Se7en", "overview": "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as motives.", "release_date": "1995-09-22", "vote_average": 8.3, "runtime": 127, "genre_ids": [80, 9648, 53], "genres": [{"id": 80, "name": "Crime"}, {"id": 9648, "name": "Mystery"}, {"id": 53, "name": "Thriller"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 819, "name": "Brad Pitt", "character": "Detective Mills", "profile_path": None}], "crew": [{"id": 7467, "name": "David Fincher", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 745, "title": "The Sixth Sense", "overview": "A boy who communicates with spirits seeks the help of a disheartened child psychologist.", "release_date": "1999-08-06", "vote_average": 7.9, "runtime": 107, "genre_ids": [9648, 53, 18], "genres": [{"id": 9648, "name": "Mystery"}, {"id": 53, "name": "Thriller"}, {"id": 18, "name": "Drama"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 819, "name": "Bruce Willis", "character": "Dr. Crowe", "profile_path": None}], "crew": [{"id": 11614, "name": "M. Night Shyamalan", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 274, "title": "The Silence of the Lambs", "overview": "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to catch another serial killer.", "release_date": "1991-02-14", "vote_average": 8.3, "runtime": 118, "genre_ids": [80, 18, 53], "genres": [{"id": 80, "name": "Crime"}, {"id": 18, "name": "Drama"}, {"id": 53, "name": "Thriller"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 6193, "name": "Jodie Foster", "character": "Clarice Starling", "profile_path": None}], "crew": [{"id": 11343, "name": "Jonathan Demme", "job": "Director"}]}, "videos": {"results": []}},

    # ── Romance ──
    {"id": 597, "title": "Titanic", "overview": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", "release_date": "1997-12-19", "vote_average": 7.9, "runtime": 194, "genre_ids": [18, 10749], "genres": [{"id": 18, "name": "Drama"}, {"id": 10749, "name": "Romance"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 6193, "name": "Leonardo DiCaprio", "character": "Jack Dawson", "profile_path": None}], "crew": [{"id": 2710, "name": "James Cameron", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 4348, "title": "Pride & Prejudice", "overview": "Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy.", "release_date": "2005-11-11", "vote_average": 7.8, "runtime": 129, "genre_ids": [18, 10749], "genres": [{"id": 18, "name": "Drama"}, {"id": 10749, "name": "Romance"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 72129, "name": "Keira Knightley", "character": "Elizabeth Bennet", "profile_path": None}], "crew": [{"id": 36232, "name": "Joe Wright", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 508442, "title": "Soul", "overview": "A musician who has lost his passion for music is transported out of his body and must find his way back with the help of an infant soul learning about herself.", "release_date": "2020-12-25", "vote_average": 8.0, "runtime": 100, "genre_ids": [16, 35, 18, 10751], "genres": [{"id": 16, "name": "Animation"}, {"id": 35, "name": "Comedy"}, {"id": 18, "name": "Drama"}, {"id": 10751, "name": "Family"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [], "crew": [{"id": 12898, "name": "Pete Docter", "job": "Director"}]}, "videos": {"results": []}},

    # ── Science Fiction ──
    {"id": 603, "title": "The Matrix", "overview": "A computer programmer discovers that reality as he knows it is a simulation created by machines, and joins a rebellion to break free.", "release_date": "1999-03-31", "vote_average": 8.2, "runtime": 136, "genre_ids": [28, 878], "genres": [{"id": 28, "name": "Action"}, {"id": 878, "name": "Science Fiction"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 6384, "name": "Keanu Reeves", "character": "Neo", "profile_path": None}], "crew": [{"id": 9340, "name": "Lana Wachowski", "job": "Director"}, {"id": 9339, "name": "Lilly Wachowski", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 157336, "title": "Interstellar", "overview": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", "release_date": "2014-11-07", "vote_average": 8.4, "runtime": 169, "genre_ids": [878, 18, 12], "genres": [{"id": 878, "name": "Science Fiction"}, {"id": 18, "name": "Drama"}, {"id": 12, "name": "Adventure"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 10297, "name": "Matthew McConaughey", "character": "Cooper", "profile_path": None}], "crew": [{"id": 525, "name": "Christopher Nolan", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 348, "title": "Alien", "overview": "After investigating a mysterious transmission of unknown origin, the crew of a commercial spaceship encounters a deadly lifeform.", "release_date": "1979-06-22", "vote_average": 8.1, "runtime": 117, "genre_ids": [878, 27], "genres": [{"id": 878, "name": "Science Fiction"}, {"id": 27, "name": "Horror"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 10205, "name": "Sigourney Weaver", "character": "Ripley", "profile_path": None}], "crew": [{"id": 578, "name": "Ridley Scott", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 264660, "title": "Ex Machina", "overview": "A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence by evaluating the human qualities of a highly advanced humanoid A.I.", "release_date": "2015-04-24", "vote_average": 7.7, "runtime": 108, "genre_ids": [878, 53], "genres": [{"id": 878, "name": "Science Fiction"}, {"id": 53, "name": "Thriller"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [], "crew": [{"id": 59839, "name": "Alex Garland", "job": "Director"}]}, "videos": {"results": []}},

    # ── War ──
    {"id": 857, "title": "Saving Private Ryan", "overview": "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.", "release_date": "1998-07-24", "vote_average": 8.2, "runtime": 169, "genre_ids": [18, 10752], "genres": [{"id": 18, "name": "Drama"}, {"id": 10752, "name": "War"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 31, "name": "Tom Hanks", "character": "Captain Miller", "profile_path": None}], "crew": [{"id": 488, "name": "Steven Spielberg", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 530, "title": "Apocalypse Now", "overview": "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces colonel who has set himself up as a god among a local tribe.", "release_date": "1979-08-15", "vote_average": 8.4, "runtime": 147, "genre_ids": [18, 10752], "genres": [{"id": 18, "name": "Drama"}, {"id": 10752, "name": "War"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 380, "name": "Marlon Brando", "character": "Colonel Kurtz", "profile_path": None}], "crew": [{"id": 1776, "name": "Francis Ford Coppola", "job": "Director"}]}, "videos": {"results": []}},

    # ── History ──
    {"id": 424, "title": "Schindler's List", "overview": "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.", "release_date": "1993-12-15", "vote_average": 8.6, "runtime": 195, "genre_ids": [18, 36, 10752], "genres": [{"id": 18, "name": "Drama"}, {"id": 36, "name": "History"}, {"id": 10752, "name": "War"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 65, "name": "Liam Neeson", "character": "Oskar Schindler", "profile_path": None}], "crew": [{"id": 488, "name": "Steven Spielberg", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 76203, "title": "12 Years a Slave", "overview": "In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.", "release_date": "2013-10-18", "vote_average": 7.9, "runtime": 134, "genre_ids": [18, 36], "genres": [{"id": 18, "name": "Drama"}, {"id": 36, "name": "History"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 17419, "name": "Chiwetel Ejiofor", "character": "Solomon Northup", "profile_path": None}], "crew": [{"id": 59839, "name": "Steve McQueen", "job": "Director"}]}, "videos": {"results": []}},

    # ── Documentary ──
    {"id": 2501, "title": "March of the Penguins", "overview": "Every winter, thousands of emperor penguins leave the ocean and walk inland to their ancestral breeding grounds in Antarctica.", "release_date": "2005-01-26", "vote_average": 7.0, "runtime": 80, "genre_ids": [99], "genres": [{"id": 99, "name": "Documentary"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [], "crew": [{"id": 24255, "name": "Luc Jacquet", "job": "Director"}]}, "videos": {"results": []}},

    # ── Music ──
    {"id": 313369, "title": "La La Land", "overview": "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.", "release_date": "2016-12-09", "vote_average": 7.9, "runtime": 128, "genre_ids": [35, 18, 10749, 10402], "genres": [{"id": 35, "name": "Comedy"}, {"id": 18, "name": "Drama"}, {"id": 10749, "name": "Romance"}, {"id": 10402, "name": "Music"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 30614, "name": "Ryan Gosling", "character": "Sebastian", "profile_path": None}], "crew": [{"id": 136495, "name": "Damien Chazelle", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 244786, "title": "Whiplash", "overview": "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.", "release_date": "2014-10-10", "vote_average": 8.4, "runtime": 107, "genre_ids": [18, 10402], "genres": [{"id": 18, "name": "Drama"}, {"id": 10402, "name": "Music"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 1038936, "name": "Miles Teller", "character": "Andrew", "profile_path": None}], "crew": [{"id": 136495, "name": "Damien Chazelle", "job": "Director"}]}, "videos": {"results": []}},

    # ── Western ──
    {"id": 429, "title": "The Good, the Bad and the Ugly", "overview": "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.", "release_date": "1966-12-23", "vote_average": 8.5, "runtime": 178, "genre_ids": [37], "genres": [{"id": 37, "name": "Western"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 190, "name": "Clint Eastwood", "character": "Blondie", "profile_path": None}], "crew": [{"id": 3556, "name": "Sergio Leone", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 68718, "title": "Django Unchained", "overview": "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.", "release_date": "2012-12-25", "vote_average": 8.2, "runtime": 165, "genre_ids": [37, 18], "genres": [{"id": 37, "name": "Western"}, {"id": 18, "name": "Drama"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 17419, "name": "Jamie Foxx", "character": "Django", "profile_path": None}], "crew": [{"id": 138, "name": "Quentin Tarantino", "job": "Director"}]}, "videos": {"results": []}},

    # ── Modern Hits ──
    {"id": 569094, "title": "Spider-Man: Across the Spider-Verse", "overview": "Miles Morales catapults across the Multiverse where he encounters a team of Spider-People charged with protecting its very existence.", "release_date": "2023-06-02", "vote_average": 8.4, "runtime": 140, "genre_ids": [16, 28, 12], "genres": [{"id": 16, "name": "Animation"}, {"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [], "crew": [{"id": 41077, "name": "Joaquim Dos Santos", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 346698, "title": "Barbie", "overview": "Barbie and Ken are having the time of their lives in the colorful Barbie Land. Then they get a chance to go to the real world, where they discover the joys and perils of living among humans.", "release_date": "2023-07-21", "vote_average": 7.0, "runtime": 114, "genre_ids": [35, 12, 14], "genres": [{"id": 35, "name": "Comedy"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 234352, "name": "Margot Robbie", "character": "Barbie", "profile_path": None}], "crew": [{"id": 45400, "name": "Greta Gerwig", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 572802, "title": "Aquaman and the Lost Kingdom", "overview": "Black Manta seeks revenge on Aquaman for his father's death. With his power to command the seas, Aquaman must forge an unlikely alliance to protect Atlantis.", "release_date": "2023-12-22", "vote_average": 6.3, "runtime": 124, "genre_ids": [28, 12, 14], "genres": [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 117642, "name": "Jason Momoa", "character": "Aquaman", "profile_path": None}], "crew": [{"id": 55934, "name": "James Wan", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 786892, "title": "Furiosa: A Mad Max Saga", "overview": "The origin story of the mighty warrior Furiosa before she teamed up with Mad Max in Fury Road.", "release_date": "2024-05-24", "vote_average": 7.6, "runtime": 148, "genre_ids": [28, 12, 878], "genres": [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 878, "name": "Science Fiction"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 1397778, "name": "Anya Taylor-Joy", "character": "Furiosa", "profile_path": None}], "crew": [{"id": 20629, "name": "George Miller", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 823464, "title": "Godzilla x Kong: The New Empire", "overview": "Two ancient titans, Godzilla and Kong, clash in an epic battle as humans unravel their intertwined origins.", "release_date": "2024-03-29", "vote_average": 7.0, "runtime": 115, "genre_ids": [28, 878, 12], "genres": [{"id": 28, "name": "Action"}, {"id": 878, "name": "Science Fiction"}, {"id": 12, "name": "Adventure"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [], "crew": [{"id": 231067, "name": "Adam Wingard", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 438631, "title": "Dune", "overview": "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family.", "release_date": "2021-10-22", "vote_average": 7.8, "runtime": 155, "genre_ids": [878, 12], "genres": [{"id": 878, "name": "Science Fiction"}, {"id": 12, "name": "Adventure"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 1190668, "name": "Timothée Chalamet", "character": "Paul Atreides", "profile_path": None}], "crew": [{"id": 137427, "name": "Denis Villeneuve", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 522627, "title": "The Batman", "overview": "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.", "release_date": "2022-03-04", "vote_average": 7.7, "runtime": 176, "genre_ids": [80, 9648, 53], "genres": [{"id": 80, "name": "Crime"}, {"id": 9648, "name": "Mystery"}, {"id": 53, "name": "Thriller"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [{"id": 11288, "name": "Robert Pattinson", "character": "Bruce Wayne / The Batman", "profile_path": None}], "crew": [{"id": 41077, "name": "Matt Reeves", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 496243, "title": "Parasite", "overview": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", "release_date": "2019-05-30", "vote_average": 8.5, "runtime": 133, "genre_ids": [35, 53, 18], "genres": [{"id": 35, "name": "Comedy"}, {"id": 53, "name": "Thriller"}, {"id": 18, "name": "Drama"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [], "crew": [{"id": 21684, "name": "Bong Joon-ho", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 299536, "title": "Avengers: Infinity War", "overview": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation puts an end to the universe.", "release_date": "2018-04-27", "vote_average": 8.3, "runtime": 149, "genre_ids": [28, 12, 878], "genres": [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 878, "name": "Science Fiction"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [], "crew": [{"id": 19272, "name": "Anthony Russo", "job": "Director"}, {"id": 19271, "name": "Joe Russo", "job": "Director"}]}, "videos": {"results": []}},
    {"id": 324857, "title": "Spider-Man: Into the Spider-Verse", "overview": "Bitten by a radioactive spider, teen Miles Morales develops spider-like powers and must use them to protect his world from a dangerous villain.", "release_date": "2018-12-14", "vote_average": 8.4, "runtime": 117, "genre_ids": [16, 28, 12], "genres": [{"id": 16, "name": "Animation"}, {"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}], "poster_path": None, "backdrop_path": None, "credits": {"cast": [], "crew": [{"id": 88675, "name": "Bob Persichetti", "job": "Director"}]}, "videos": {"results": []}},
]
# fmt: on

_MOVIE_INDEX: dict[int, dict] = {m["id"]: m for m in DEMO_MOVIES}


def get_demo_movie(movie_id: int) -> dict | None:
    return _MOVIE_INDEX.get(movie_id)


def get_demo_movies_page(collection: str, page: int = 1) -> dict:
    """Return a page of demo movies sliced by pseudo-collection."""
    page_size = 10
    if collection == "trending":
        pool = DEMO_MOVIES[:10]
    elif collection == "popular":
        pool = sorted(DEMO_MOVIES, key=lambda m: m["vote_average"], reverse=True)[:20]
    elif collection == "top_rated":
        pool = sorted(DEMO_MOVIES, key=lambda m: m["vote_average"], reverse=True)
    elif collection == "upcoming":
        pool = sorted(DEMO_MOVIES, key=lambda m: m.get("release_date", ""), reverse=True)[:20]
    else:
        pool = DEMO_MOVIES

    start = (page - 1) * page_size
    end = start + page_size
    results = pool[start:end]
    import math
    return {
        "page": page,
        "results": results,
        "total_pages": math.ceil(len(pool) / page_size),
        "total_results": len(pool),
    }


def search_demo_movies(query: str | None, genre: str | None, min_rating: float | None, sort_by: str | None) -> list[dict]:
    results = list(DEMO_MOVIES)
    if query:
        q = query.lower()
        results = [m for m in results if q in m["title"].lower() or q in m.get("overview", "").lower()]
    if genre:
        genre_ids = {int(g) for g in genre.split(",") if g.isdigit()}
        results = [m for m in results if genre_ids.intersection(set(m.get("genre_ids", [])))]
    if min_rating is not None:
        results = [m for m in results if (m.get("vote_average") or 0) >= min_rating]

    key = sort_by or "popularity.desc"
    if key == "vote_average.desc":
        results.sort(key=lambda m: m.get("vote_average") or 0, reverse=True)
    elif key == "primary_release_date.desc":
        results.sort(key=lambda m: m.get("release_date") or "", reverse=True)
    elif key == "primary_release_date.asc":
        results.sort(key=lambda m: m.get("release_date") or "")
    elif key == "title.asc":
        results.sort(key=lambda m: m.get("title") or "")

    return results
